"""Script to generate kalkulasi_manual.ipynb"""
import json, uuid

def mid(source):
    return {"cell_type": "markdown", "id": str(uuid.uuid4())[:8], "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "id": str(uuid.uuid4())[:8], "metadata": {}, "outputs": [], "execution_count": None, "source": source}

cells = []

# Title
cells.append(mid(
    "# Kalkulasi Manual: Pipeline Prediksi Harga Perak\n"
    "## Prophet + XGBoost / LightGBM — Step-by-Step Walkthrough\n\n"
    "Notebook ini menampilkan **seluruh perhitungan** pipeline prediksi harga perak secara transparan\n"
    "menggunakan 10 data riil dari Yahoo Finance.\n\n"
    "Pipeline mengikuti implementasi `forecaster.py` (versi web app).\n\n"
    "**Struktur:**\n"
    "1. Download & seleksi data\n"
    "2. Feature engineering (lag, rolling, RSI, MACD, Bollinger, ATR, cross-asset, kalender)\n"
    "3. Prophet fitting dan dekomposisi komponen\n"
    "4. Log return target\n"
    "5. Training XGBoost & LightGBM\n"
    "6. Prediksi dan konversi ke harga\n"
    "7. Evaluasi metrik (RMSE, MAE, MAPE, R2)"
))

# Cell 1: Imports
cells.append(code(
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n\n"
    "import pandas as pd\n"
    "import numpy as np\n"
    "import yfinance as yf\n"
    "import math\n"
    "from prophet import Prophet\n"
    "from xgboost import XGBRegressor\n"
    "from lightgbm import LGBMRegressor\n"
    "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n\n"
    "pd.set_option('display.float_format', '{:.6f}'.format)\n"
    "pd.set_option('display.max_columns', None)\n"
    "pd.set_option('display.width', 300)\n"
    'print("Semua library berhasil diimpor.")'
))

# Section 1: Download Data
cells.append(mid(
    "## 1. Download Data dari Yahoo Finance\n\n"
    "Download 6 bulan data historis (~130 hari trading) untuk 4 variabel:\n\n"
    "| Ticker | Variabel | Satuan |\n"
    "|--------|----------|--------|\n"
    "| `SI=F` | Harga Perak | USD/troy oz |\n"
    "| `GC=F` | Harga Emas | USD/troy oz |\n"
    "| `CL=F` | Harga Minyak WTI | USD/barrel |\n"
    "| `DX-Y.NYB` | Indeks Dolar AS | USD Index |\n\n"
    "Data 6 bulan diperlukan agar fitur lag_14 dan rolling_30 dapat dihitung dengan benar."
))

cells.append(code(
    "TICKERS_MAP = {'SI=F': 'silver', 'GC=F': 'gold', 'CL=F': 'oil', 'DX-Y.NYB': 'usd'}\n"
    "SERIES_LIST = ['silver', 'gold', 'oil', 'usd']\n"
    "LAG_DAYS        = [1, 2, 3, 5, 7, 10, 14]\n"
    "ROLLING_WINDOWS = [5, 10, 20, 30]\n\n"
    "print('Mengunduh data dari Yahoo Finance...')\n"
    "raw = yf.download(\n"
    "    list(TICKERS_MAP.keys()),\n"
    "    period='6mo',\n"
    "    interval='1d',\n"
    "    auto_adjust=True,\n"
    "    progress=False\n"
    ")\n\n"
    "close_raw = raw['Close'].copy()\n"
    "close_raw = close_raw.rename(columns=TICKERS_MAP)[SERIES_LIST]\n"
    "close_raw = close_raw.dropna().reset_index()\n"
    "close_raw = close_raw.rename(columns={'Date': 'ds'})\n"
    "close_raw['ds'] = pd.to_datetime(close_raw['ds'])\n"
    "if close_raw['ds'].dt.tz is not None:\n"
    "    close_raw['ds'] = close_raw['ds'].dt.tz_localize(None)\n\n"
    "print(f'Total baris berhasil diunduh: {len(close_raw)}')\n"
    "print(f'Rentang tanggal: {close_raw[\"ds\"].min().date()} s/d {close_raw[\"ds\"].max().date()}')\n"
    "print()\n"
    "print('15 baris terakhir:')\n"
    "close_raw[['ds','silver','gold','oil','usd']].tail(15).reset_index(drop=True)"
))

# Section 2: Sample Selection
cells.append(mid(
    "## 2. Seleksi Sampel Demo (10 Baris Terakhir)\n\n"
    "Fitur dihitung dari seluruh dataset agar lag dan rolling terkompilasi dengan benar.\n"
    "Kemudian kita ambil **10 baris terakhir** sebagai sampel demonstrasi.\n\n"
    "**Split:**\n"
    "- Baris 0–7 (8 baris) → **Training set**\n"
    "- Baris 8–9 (2 baris) → **Test set** (evaluasi)"
))

cells.append(code(
    "df_all = close_raw.copy().reset_index(drop=True)\n"
    "N_SAMPLE = 10\n"
    "N_TRAIN  = 8\n"
    "N_TEST   = 2\n\n"
    "print(f'Dataset total: {len(df_all)} baris')\n"
    "print(f'Demo: 10 baris terakhir  |  Train: {N_TRAIN}  |  Test: {N_TEST}')\n"
    "print()\n\n"
    "# Compute all non-Prophet features on full dataset\n"
    "df = df_all.copy()\n\n"
    "feat_dict = {}\n"
    "for series in SERIES_LIST:\n"
    "    ret = df[series].pct_change()\n"
    "    for lag in LAG_DAYS:\n"
    "        feat_dict[f'{series}_lag_{lag}']     = df[series].shift(lag)\n"
    "        feat_dict[f'{series}_ret_lag_{lag}'] = ret.shift(lag)\n"
    "    for w in ROLLING_WINDOWS:\n"
    "        feat_dict[f'{series}_roll_mean_{w}'] = df[series].rolling(w).mean()\n"
    "        feat_dict[f'{series}_roll_std_{w}']  = df[series].rolling(w).std()\n\n"
    "# Technical indicators (all shifted by 1 to avoid look-ahead)\n"
    "delta    = df['silver'].diff()\n"
    "up, down = delta.clip(lower=0), (-delta).clip(lower=0)\n"
    "avg_up14 = up.rolling(14).mean()\n"
    "avg_dn14 = down.rolling(14).mean().replace(0, 1e-9)\n"
    "feat_dict['silver_rsi_14'] = (100 - 100 / (1 + avg_up14 / avg_dn14)).shift(1)\n\n"
    "ema12 = df['silver'].ewm(span=12, adjust=False).mean()\n"
    "ema26 = df['silver'].ewm(span=26, adjust=False).mean()\n"
    "macd  = ema12 - ema26\n"
    "feat_dict['silver_macd']        = macd.shift(1)\n"
    "feat_dict['silver_macd_signal'] = macd.ewm(span=9, adjust=False).mean().shift(1)\n\n"
    "rm20 = df['silver'].rolling(20).mean()\n"
    "rs20 = df['silver'].rolling(20).std().replace(0, 1e-9)\n"
    "feat_dict['silver_bb_pos'] = ((df['silver'] - rm20) / rs20).shift(1)\n"
    "feat_dict['silver_atr_14'] = df['silver'].diff().abs().rolling(14).mean().shift(1)\n\n"
    "gs = df['gold']   / df['silver'].replace(0, 1e-9)\n"
    "so = df['silver'] / df['oil'].replace(0, 1e-9)\n"
    "feat_dict['gold_silver_ratio_lag_1'] = gs.shift(1)\n"
    "feat_dict['gold_silver_ratio_lag_5'] = gs.shift(5)\n"
    "feat_dict['silver_oil_ratio_lag_1']  = so.shift(1)\n\n"
    "feat_dict['day_of_week'] = df['ds'].dt.dayofweek\n"
    "feat_dict['month']       = df['ds'].dt.month\n\n"
    "df_feats = pd.concat([df, pd.DataFrame(feat_dict, index=df.index)], axis=1)\n"
    "df_clean = df_feats.dropna().reset_index(drop=True)\n"
    "df_demo  = df_clean.tail(N_SAMPLE).reset_index(drop=True)\n\n"
    "print(f'Baris setelah dropna: {len(df_clean)}')\n"
    "print(f'Sampel demo ({N_SAMPLE} baris):')\n"
    "print(df_demo[['ds','silver','gold','oil','usd']].to_string())"
))

# Section 3: Lag Features
cells.append(mid(
    "## 3. Feature Engineering: Lag Features\n\n"
    "Untuk setiap 4 variabel, kita buat:\n"
    "- **Price lag**: `{series}_lag_{d}[t] = price[t - d]`\n"
    "- **Return lag**: `{series}_ret_lag_{d}[t] = (price[t-d] - price[t-d-1]) / price[t-d-1]`\n\n"
    "Lag days: d ∈ {1, 2, 3, 5, 7, 10, 14}\n\n"
    "Total: 4 variabel × 7 lag × 2 (price + return) = **56 fitur**"
))

cells.append(code(
    "# Silver price lag features (demo rows only)\n"
    "lag_cols_price = [f'silver_lag_{d}' for d in LAG_DAYS]\n"
    "lag_cols_ret   = [f'silver_ret_lag_{d}' for d in LAG_DAYS]\n\n"
    "lag_df = df_demo[['ds','silver'] + lag_cols_price + lag_cols_ret].copy()\n"
    "print('Silver Lag Features (10 baris demo):')\n"
    "print(lag_df.to_string())\n"
    "print()\n\n"
    "# Manual verification for last row\n"
    "last_full_idx = len(df_clean) - 1\n"
    "print('Verifikasi baris terakhir (indeks 9 dalam demo):')\n"
    "sv = df_clean['silver']\n"
    "for d in [1, 2, 3]:\n"
    "    price_d = df_clean['silver'].iloc[last_full_idx - d]\n"
    "    price_d1 = df_clean['silver'].iloc[last_full_idx - d - 1]\n"
    "    ret_d = (price_d - price_d1) / price_d1\n"
    "    print(f'  silver_lag_{d}     = silver[t-{d}] = {price_d:.6f}')\n"
    "    print(f'  silver_ret_lag_{d} = ({price_d:.4f} - {price_d1:.4f}) / {price_d1:.4f} = {ret_d:.8f}')"
))

# Section 4: Rolling Stats
cells.append(mid(
    "## 4. Feature Engineering: Rolling Statistics\n\n"
    "Untuk setiap variabel:\n"
    "- `roll_mean_w[t] = mean(price[t-w+1 .. t])`\n"
    "- `roll_std_w[t]  = std(price[t-w+1 .. t])`\n\n"
    "Window w ∈ {5, 10, 20, 30}\n\n"
    "Total: 4 × 4 × 2 = **32 fitur**"
))

cells.append(code(
    "roll_cols_show = ([f'silver_roll_mean_{w}' for w in ROLLING_WINDOWS]\n"
    "                + [f'silver_roll_std_{w}'  for w in ROLLING_WINDOWS])\n\n"
    "roll_df = df_demo[['ds','silver'] + roll_cols_show].copy()\n"
    "print('Silver Rolling Features (10 baris demo):')\n"
    "print(roll_df.to_string())\n"
    "print()\n\n"
    "# Manual verification: roll_mean_5 for last row\n"
    "last_idx = len(df_clean) - 1\n"
    "w5_data = df_clean['silver'].iloc[last_idx-4:last_idx+1].values\n"
    "print(f'Verifikasi silver_roll_mean_5 baris terakhir:')\n"
    "print(f'  5 harga silver: {[round(x,4) for x in w5_data]}')\n"
    "print(f'  mean = sum / 5 = {sum(w5_data):.6f} / 5 = {np.mean(w5_data):.6f}')\n"
    "print()\n"
    "w30_data = df_clean['silver'].iloc[last_idx-29:last_idx+1].values\n"
    "print(f'Verifikasi silver_roll_std_30 baris terakhir (ddof=1):')\n"
    "print(f'  mean_30 = {np.mean(w30_data):.6f}')\n"
    "print(f'  std_30  = {np.std(w30_data, ddof=1):.6f}')"
))

# Section 5: RSI
cells.append(mid(
    "## 5. Feature Engineering: RSI(14)\n\n"
    "RSI (Relative Strength Index) mengukur momentum harga.\n\n"
    "**Formula:**\n"
    "```\n"
    "delta[t]   = silver[t] - silver[t-1]\n"
    "avg_up     = mean(max(delta, 0)) selama 14 periode\n"
    "avg_down   = mean(max(-delta, 0)) selama 14 periode\n"
    "RS         = avg_up / avg_down\n"
    "RSI        = 100 - (100 / (1 + RS))\n"
    "```\n\n"
    "RSI > 70 → overbought, RSI < 30 → oversold.\n"
    "Fitur di-**shift(1)** sehingga hanya menggunakan informasi t-1 ke belakang."
))

cells.append(code(
    "rsi_df = df_demo[['ds','silver','silver_rsi_14']].copy()\n"
    "# Also compute raw (unshifted) for reference\n"
    "delta_s = df_all['silver'].diff()\n"
    "up_s    = delta_s.clip(lower=0)\n"
    "dn_s    = (-delta_s).clip(lower=0)\n"
    "rsi_raw_full = (100 - 100 / (1 + up_s.rolling(14).mean() /\n"
    "                              dn_s.rolling(14).mean().replace(0,1e-9)))\n\n"
    "print('RSI(14) - 10 baris demo:')\n"
    "print('  silver_rsi_14 = shift(1) dari RSI, artinya RSI yang dihitung di hari sebelumnya')\n"
    "print(rsi_df.to_string())\n"
    "print()\n\n"
    "# Step-by-step for last row (t), before shift\n"
    "last = len(df_all) - 1\n"
    "win15 = df_all['silver'].iloc[last-14:last+1].values\n"
    "deltas14 = np.diff(win15)\n"
    "ups14    = np.where(deltas14 > 0, deltas14, 0.0)\n"
    "dns14    = np.where(deltas14 < 0, -deltas14, 0.0)\n"
    "avg_up_m  = np.mean(ups14)\n"
    "avg_dn_m  = np.mean(dns14) if np.mean(dns14) > 0 else 1e-9\n"
    "rs_m      = avg_up_m / avg_dn_m\n"
    "rsi_m     = 100 - 100 / (1 + rs_m)\n\n"
    "print('Perhitungan manual RSI untuk baris terakhir (t, sebelum shift):')\n"
    "print(f'  15 harga silver: {[round(x,4) for x in win15]}')\n"
    "print(f'  14 delta: {[round(x,6) for x in deltas14]}')\n"
    "print(f'  Up changes:   {[round(x,6) for x in ups14]}')\n"
    "print(f'  Down changes: {[round(x,6) for x in dns14]}')\n"
    "print(f'  avg_up   = {avg_up_m:.8f}')\n"
    "print(f'  avg_down = {avg_dn_m:.8f}')\n"
    "print(f'  RS  = {avg_up_m:.8f} / {avg_dn_m:.8f} = {rs_m:.8f}')\n"
    "print(f'  RSI = 100 - 100/(1+{rs_m:.8f}) = {rsi_m:.8f}')\n"
    "print(f'  (nilai ini menjadi silver_rsi_14 untuk baris BERIKUTNYA karena shift(1))')"
))

# Section 6: MACD
cells.append(mid(
    "## 6. Feature Engineering: MACD\n\n"
    "MACD (Moving Average Convergence Divergence) mengukur momentum berbasis EMA.\n\n"
    "**Formula:**\n"
    "```\n"
    "alpha_12 = 2 / (12 + 1) = 0.1538\n"
    "alpha_26 = 2 / (26 + 1) = 0.0741\n"
    "EMA_12[t] = alpha_12 * price[t] + (1 - alpha_12) * EMA_12[t-1]\n"
    "EMA_26[t] = alpha_26 * price[t] + (1 - alpha_26) * EMA_26[t-1]\n"
    "MACD[t]   = EMA_12[t] - EMA_26[t]\n"
    "Signal[t] = EMA_9(MACD)\n"
    "```\n\n"
    "Semua di-**shift(1)** untuk mencegah look-ahead."
))

cells.append(code(
    "ema12_full = df_all['silver'].ewm(span=12, adjust=False).mean()\n"
    "ema26_full = df_all['silver'].ewm(span=26, adjust=False).mean()\n"
    "macd_full  = ema12_full - ema26_full\n\n"
    "alpha12 = 2.0 / (12 + 1)\n"
    "alpha26 = 2.0 / (26 + 1)\n"
    "alpha9  = 2.0 / (9 + 1)\n"
    "print(f'alpha_12 = 2/(12+1) = {alpha12:.6f}')\n"
    "print(f'alpha_26 = 2/(26+1) = {alpha26:.6f}')\n"
    "print(f'alpha_9  = 2/(9+1)  = {alpha9:.6f}')\n"
    "print()\n\n"
    "macd_display = pd.DataFrame({\n"
    "    'ds':                df_demo['ds'].values,\n"
    "    'silver':            df_demo['silver'].values,\n"
    "    'ema12':             ema12_full.tail(N_SAMPLE).values,\n"
    "    'ema26':             ema26_full.tail(N_SAMPLE).values,\n"
    "    'macd_raw':          macd_full.tail(N_SAMPLE).values,\n"
    "    'silver_macd':       df_demo['silver_macd'].values,\n"
    "    'silver_macd_signal':df_demo['silver_macd_signal'].values,\n"
    "})\n"
    "print('MACD - 10 baris demo:')\n"
    "print(macd_display.to_string())\n"
    "print()\n\n"
    "# Manual for last 3 rows\n"
    "last = len(df_all) - 1\n"
    "print('Manual EMA untuk 3 baris terakhir:')\n"
    "for i in [last-2, last-1, last]:\n"
    "    sv   = df_all['silver'].iloc[i]\n"
    "    e12  = ema12_full.iloc[i]\n"
    "    e12p = ema12_full.iloc[i-1]\n"
    "    e26  = ema26_full.iloc[i]\n"
    "    e26p = ema26_full.iloc[i-1]\n"
    "    print(f'  t={i}: price={sv:.4f}')\n"
    "    print(f'    EMA12 = {alpha12:.4f}x{sv:.4f} + {1-alpha12:.4f}x{e12p:.4f} = {e12:.6f}')\n"
    "    print(f'    EMA26 = {alpha26:.4f}x{sv:.4f} + {1-alpha26:.4f}x{e26p:.4f} = {e26:.6f}')\n"
    "    print(f'    MACD  = {e12:.6f} - {e26:.6f} = {macd_full.iloc[i]:.6f}')"
))

# Section 7: Bollinger + ATR
cells.append(mid(
    "## 7. Feature Engineering: Bollinger Band Position & ATR(14)\n\n"
    "**Bollinger Band Position** — posisi harga relatif terhadap pita Bollinger 20-hari:\n"
    "```\n"
    "BB_pos[t] = (price[t] - mean_20[t]) / std_20[t]\n"
    "```\n"
    "BB_pos = 0 → di tengah, BB_pos = +2 → upper band, BB_pos = -2 → lower band.\n\n"
    "**ATR(14) — Average True Range**:\n"
    "```\n"
    "ATR_14[t] = mean(|price[t] - price[t-1]|) untuk 14 periode terakhir\n"
    "```\n\n"
    "Keduanya di-**shift(1)**."
))

cells.append(code(
    "bb_atr_df = pd.DataFrame({\n"
    "    'ds':            df_demo['ds'].values,\n"
    "    'silver':        df_demo['silver'].values,\n"
    "    'silver_bb_pos': df_demo['silver_bb_pos'].values,\n"
    "    'silver_atr_14': df_demo['silver_atr_14'].values,\n"
    "})\n"
    "print('Bollinger Band Position & ATR(14) - 10 baris demo:')\n"
    "print(bb_atr_df.to_string())\n"
    "print()\n\n"
    "# Manual for last row (t), before shift\n"
    "last = len(df_all) - 1\n"
    "w20  = df_all['silver'].iloc[last-19:last+1].values\n"
    "mean20 = np.mean(w20)\n"
    "std20  = np.std(w20, ddof=1)\n"
    "bb_m   = (df_all['silver'].iloc[last] - mean20) / (std20 if std20 > 0 else 1e-9)\n"
    "w14d   = np.abs(np.diff(df_all['silver'].iloc[last-14:last+1].values))\n"
    "atr_m  = np.mean(w14d)\n\n"
    "print(f'Manual untuk baris terakhir (t={last}, sebelum shift):')\n"
    "print(f'  20 harga silver: {[round(x,4) for x in w20[:5]]} ... {[round(x,4) for x in w20[-5:]]}')\n"
    "print(f'  mean_20 = {mean20:.6f}')\n"
    "print(f'  std_20  = {std20:.6f}')\n"
    "print(f'  BB_pos  = ({df_all[\"silver\"].iloc[last]:.6f} - {mean20:.6f}) / {std20:.6f} = {bb_m:.6f}')\n"
    "print(f'  14 |delta|: {[round(x,6) for x in w14d]}')\n"
    "print(f'  ATR_14 = mean = {atr_m:.6f}')"
))

# Section 8: Cross-Asset Ratios
cells.append(mid(
    "## 8. Feature Engineering: Cross-Asset Ratios\n\n"
    "Rasio antar aset menangkap hubungan relatif:\n\n"
    "| Fitur | Formula | Makna |\n"
    "|-------|---------|-------|\n"
    "| `gold_silver_ratio_lag_1` | gold[t-1] / silver[t-1] | Gold/Silver Ratio kemarin |\n"
    "| `gold_silver_ratio_lag_5` | gold[t-5] / silver[t-5] | G/S Ratio 1 minggu lalu |\n"
    "| `silver_oil_ratio_lag_1` | silver[t-1] / oil[t-1] | Silver/Oil Ratio kemarin |\n\n"
    "Semua sudah di-lag (hanya data masa lalu)."
))

cells.append(code(
    "ratio_df = pd.DataFrame({\n"
    "    'ds':                        df_demo['ds'].values,\n"
    "    'silver':                    df_demo['silver'].values,\n"
    "    'gold':                      df_demo['gold'].values,\n"
    "    'oil':                       df_demo['oil'].values,\n"
    "    'gold_silver_ratio_lag_1':   df_demo['gold_silver_ratio_lag_1'].values,\n"
    "    'gold_silver_ratio_lag_5':   df_demo['gold_silver_ratio_lag_5'].values,\n"
    "    'silver_oil_ratio_lag_1':    df_demo['silver_oil_ratio_lag_1'].values,\n"
    "})\n"
    "print('Cross-Asset Ratio Features - 10 baris demo:')\n"
    "print(ratio_df.to_string())\n"
    "print()\n\n"
    "# Manual for last row\n"
    "last = len(df_clean) - 1\n"
    "g1  = df_clean['gold'].iloc[last-1]\n"
    "s1  = df_clean['silver'].iloc[last-1]\n"
    "s5  = df_clean['silver'].iloc[last-5]\n"
    "g5  = df_clean['gold'].iloc[last-5]\n"
    "o1  = df_clean['oil'].iloc[last-1]\n"
    "print(f'Verifikasi baris terakhir:')\n"
    "print(f'  gold_silver_ratio_lag_1 = gold[t-1]/silver[t-1] = {g1:.4f}/{s1:.4f} = {g1/s1:.6f}')\n"
    "print(f'  gold_silver_ratio_lag_5 = gold[t-5]/silver[t-5] = {g5:.4f}/{s5:.4f} = {g5/s5:.6f}')\n"
    "print(f'  silver_oil_ratio_lag_1  = silver[t-1]/oil[t-1] = {s1:.4f}/{o1:.4f} = {s1/o1:.6f}')"
))

# Section 9: Calendar
cells.append(mid(
    "## 9. Feature Engineering: Calendar Features\n\n"
    "- **`day_of_week`**: 0=Senin, 1=Selasa, ..., 4=Jumat\n"
    "- **`month`**: 1–12\n\n"
    "Fitur kalender membantu model menangkap efek hari-dalam-minggu dan musiman bulanan."
))

cells.append(code(
    "cal_df = pd.DataFrame({\n"
    "    'ds':          df_demo['ds'].values,\n"
    "    'silver':      df_demo['silver'].values,\n"
    "    'day_of_week': df_demo['day_of_week'].values.astype(int),\n"
    "    'day_name':    [d.strftime('%A') for d in pd.to_datetime(df_demo['ds'])],\n"
    "    'month':       df_demo['month'].values.astype(int),\n"
    "    'month_name':  [d.strftime('%B') for d in pd.to_datetime(df_demo['ds'])],\n"
    "})\n"
    "print('Calendar Features - 10 baris demo:')\n"
    "print(cal_df.to_string())"
))

# Section 10: Prophet 
cells.append(mid(
    "## 10. Prophet: Fitting & Dekomposisi Komponen\n\n"
    "Prophet mendekomposisi deret waktu:\n"
    "```\n"
    "y(t) = trend(t) * (1 + weekly(t)) * (1 + yearly(t))   [multiplicative mode]\n"
    "```\n\n"
    "**Konfigurasi:**\n"
    "- `seasonality_mode = 'multiplicative'`\n"
    "- `changepoint_prior_scale = 0.15`\n"
    "- `weekly_seasonality = True, yearly_seasonality = True`\n\n"
    "**Penting:** Prophet dilatih pada **8 baris train** untuk demo ini.\n"
    "Dengan data sebanyak ini, yearly seasonality tidak dapat dipelajari dengan baik — ini normal.\n"
    "Dalam produksi, Prophet dilatih pada ~2500 baris (10 tahun data).\n\n"
    "Output Prophet yang digunakan sebagai fitur: `ph_yhat`, `ph_trend`, `ph_weekly`, `ph_yearly`"
))

cells.append(code(
    "# Train/test split\n"
    "df_train = df_demo.iloc[:N_TRAIN].copy().reset_index(drop=True)\n"
    "df_test  = df_demo.iloc[N_TRAIN:].copy().reset_index(drop=True)\n\n"
    "print(f'Train: {N_TRAIN} baris ({df_train[\"ds\"].iloc[0].date()} s/d {df_train[\"ds\"].iloc[-1].date()})')\n"
    "print(f'Test : {N_TEST} baris  ({df_test[\"ds\"].iloc[0].date()} s/d {df_test[\"ds\"].iloc[-1].date()})')\n"
    "print()\n\n"
    "prophet_input = df_train[['ds','silver']].rename(columns={'silver':'y'})\n"
    "print('Data input ke Prophet (y = harga silver):')\n"
    "print(prophet_input.to_string())\n"
    "print()\n\n"
    "m_prophet = Prophet(\n"
    "    daily_seasonality=False,\n"
    "    weekly_seasonality=True,\n"
    "    yearly_seasonality=True,\n"
    "    changepoint_prior_scale=0.15,\n"
    "    seasonality_mode='multiplicative',\n"
    "    uncertainty_samples=0,\n"
    ")\n"
    "m_prophet.fit(prophet_input)\n"
    "print('Prophet berhasil di-fit.')"
))

cells.append(code(
    "# Predict for all 10 demo rows\n"
    "ph_fc = m_prophet.predict(df_demo[['ds']].copy())\n"
    "ph_comp = ph_fc[['ds','yhat','trend']].copy()\n"
    "ph_comp['weekly'] = ph_fc['weekly'] if 'weekly' in ph_fc.columns else 0.0\n"
    "ph_comp['yearly'] = ph_fc['yearly'] if 'yearly' in ph_fc.columns else 0.0\n"
    "ph_comp.insert(1, 'silver_actual', df_demo['silver'].values)\n"
    "ph_comp.columns = ['ds','silver_actual','ph_yhat','ph_trend','ph_weekly','ph_yearly']\n\n"
    "print('Komponen Prophet untuk 10 baris demo:')\n"
    "print(ph_comp.to_string())\n"
    "print()\n"
    "print('Catatan kolom:')\n"
    "print('  ph_yhat   : prediksi Prophet')\n"
    "print('  ph_trend  : komponen tren jangka panjang')\n"
    "print('  ph_weekly : efek hari-dalam-minggu')\n"
    "print('  ph_yearly : efek musiman tahunan')\n\n"
    "# Add Prophet features to df_demo\n"
    "df_demo['ph_yhat']   = ph_fc['yhat'].values\n"
    "df_demo['ph_trend']  = ph_fc['trend'].values\n"
    "df_demo['ph_weekly'] = ph_fc['weekly'].values if 'weekly' in ph_fc.columns else 0.0\n"
    "df_demo['ph_yearly'] = ph_fc['yearly'].values if 'yearly' in ph_fc.columns else 0.0\n"
    "print('Fitur Prophet ditambahkan ke df_demo.')"
))

# Section 11: Log Return Target 
cells.append(mid(
    "## 11. Target: Log Return 1-Step\n\n"
    "Model tidak memprediksi harga langsung, melainkan **log return**:\n"
    "```\n"
    "y[t] = log(silver[t] / silver[t-1])\n"
    "```\n\n"
    "**Mengapa log return?**\n"
    "- Lebih stasioner dari harga absolut\n"
    "- Simetris: +10% dan -10% memiliki magnitude sama\n"
    "- Mudah dibalik: `price[t] = price[t-1] × exp(y_pred[t])`"
))

cells.append(code(
    "silver_t  = df_demo['silver'].values\n"
    "silver_t1 = df_demo['silver_lag_1'].values  # silver[t-1] dari fitur lag\n\n"
    "log_ret = np.where(silver_t1 > 0, np.log(silver_t / silver_t1), 0.0)\n\n"
    "logret_df = pd.DataFrame({\n"
    "    'ds':          df_demo['ds'].values,\n"
    "    'silver[t]':   silver_t,\n"
    "    'silver[t-1]': silver_t1,\n"
    "    'ratio':       silver_t / silver_t1,\n"
    "    'log_return':  log_ret,\n"
    "    'split':       ['TRAIN'] * N_TRAIN + ['TEST'] * N_TEST,\n"
    "})\n"
    "print('Log Return Target:')\n"
    "print(logret_df.to_string())\n"
    "print()\n\n"
    "# Manual verification\n"
    "print('Verifikasi manual (rumus: log(silver[t] / silver[t-1])):')\n"
    "for i in [0, 1, 7]:\n"
    "    st  = silver_t[i]\n"
    "    st1 = silver_t1[i]\n"
    "    lr  = math.log(st / st1)\n"
    "    print(f'  Baris {i}: log({st:.6f} / {st1:.6f}) = log({st/st1:.8f}) = {lr:.8f}')\n\n"
    "y_train = log_ret[:N_TRAIN]\n"
    "actual_test_prices = silver_t[N_TRAIN:]\n"
    "prev_prices_test   = silver_t1[N_TRAIN:]\n\n"
    "print()\n"
    "print(f'y_train (8 log returns): {[round(x,8) for x in y_train]}')\n"
    "print(f'Harga aktual test:       {[round(x,4) for x in actual_test_prices]}')\n"
    "print(f'Harga sebelumnya (t-1):  {[round(x,4) for x in prev_prices_test]}')"
))

# Section 12: Feature Matrix 
cells.append(mid(
    "## 12. Matriks Fitur Final (X)\n\n"
    "Gabungkan semua fitur sesuai urutan di `forecaster.py`:\n\n"
    "| Grup | Jumlah Fitur |\n"
    "|------|--------------|\n"
    "| Price lag (4 var × 7 lag) | 28 |\n"
    "| Return lag (4 var × 7 lag) | 28 |\n"
    "| Rolling mean/std (4 var × 4 window × 2) | 32 |\n"
    "| Calendar (day_of_week, month) | 2 |\n"
    "| Prophet (yhat, trend, weekly, yearly) | 4 |\n"
    "| Technical (RSI, MACD, signal, BB, ATR) | 5 |\n"
    "| Cross-asset ratios | 3 |\n"
    "| **Total** | **102** |"
))

cells.append(code(
    "price_lag_cols = [f'{s}_lag_{d}'     for s in SERIES_LIST for d in LAG_DAYS]\n"
    "ret_lag_cols   = [f'{s}_ret_lag_{d}' for s in SERIES_LIST for d in LAG_DAYS]\n"
    "roll_cols_all  = [f'{s}_{fn}_{w}'\n"
    "                  for s in SERIES_LIST\n"
    "                  for fn in ['roll_mean','roll_std']\n"
    "                  for w in ROLLING_WINDOWS]\n"
    "calendar_cols  = ['day_of_week', 'month']\n"
    "prophet_cols   = ['ph_yhat', 'ph_trend', 'ph_weekly', 'ph_yearly']\n"
    "tech_cols      = ['silver_rsi_14','silver_macd','silver_macd_signal','silver_bb_pos','silver_atr_14']\n"
    "ratio_cols     = ['gold_silver_ratio_lag_1','gold_silver_ratio_lag_5','silver_oil_ratio_lag_1']\n"
    "feature_cols   = price_lag_cols + ret_lag_cols + roll_cols_all + calendar_cols + prophet_cols + tech_cols + ratio_cols\n\n"
    "print(f'Total fitur: {len(feature_cols)}')\n"
    "print()\n\n"
    "X_all   = df_demo[feature_cols].values\n"
    "X_train = X_all[:N_TRAIN]\n"
    "X_test  = X_all[N_TRAIN:]\n\n"
    "print(f'X_train shape: {X_train.shape}  (8 baris × 102 fitur)')\n"
    "print(f'X_test  shape: {X_test.shape}  (2 baris × 102 fitur)')\n"
    "print()\n\n"
    "# Show first 10 features of X_train as DataFrame\n"
    "X_train_show = pd.DataFrame(X_train[:, :10], columns=feature_cols[:10])\n"
    "X_train_show.insert(0, 'ds', df_demo['ds'].iloc[:N_TRAIN].values)\n"
    "print('X_train — 10 fitur pertama (dari 102):')\n"
    "print(X_train_show.to_string())\n"
    "print()\n"
    "# Show last 10 features\n"
    "X_train_show2 = pd.DataFrame(X_train[:, -10:], columns=feature_cols[-10:])\n"
    "X_train_show2.insert(0, 'ds', df_demo['ds'].iloc[:N_TRAIN].values)\n"
    "print('X_train — 10 fitur terakhir (dari 102):')\n"
    "print(X_train_show2.to_string())"
))

# Section 13: XGBoost 
cells.append(mid(
    "## 13. Training & Prediksi XGBoost\n\n"
    "XGBoost membangun ensemble pohon keputusan secara sekuensial (gradient boosting).\n\n"
    "**Konfigurasi (dari `forecaster.py`):**\n"
    "```python\n"
    "XGBRegressor(\n"
    "    n_estimators=1200, learning_rate=0.01, max_depth=6,\n"
    "    subsample=0.8, colsample_bytree=0.7,\n"
    "    reg_alpha=0.1, reg_lambda=1.0, min_child_weight=3\n"
    ")\n"
    "```\n\n"
    "**Input X_train** (8×102), **Target y_train** (8 log returns)\n\n"
    "**Prediksi → Log Return → Harga:**\n"
    "```\n"
    "log_ret_pred = xgb.predict(X_test_row)\n"
    "price_pred   = price[t-1] × exp(log_ret_pred)\n"
    "```"
))

cells.append(code(
    "xgb_model = XGBRegressor(\n"
    "    n_estimators=1200, learning_rate=0.01, max_depth=6,\n"
    "    subsample=0.8, colsample_bytree=0.7,\n"
    "    reg_alpha=0.1, reg_lambda=1.0, min_child_weight=3,\n"
    "    random_state=42, verbosity=0,\n"
    ")\n"
    "print('Training XGBoost...')\n"
    "xgb_model.fit(X_train, y_train)\n"
    "print('Selesai.')\n"
    "print()\n\n"
    "xgb_log_pred   = xgb_model.predict(X_test)\n"
    "xgb_price_pred = prev_prices_test * np.exp(xgb_log_pred)\n\n"
    "print('Prediksi XGBoost untuk 2 baris test:')\n"
    "for i in range(N_TEST):\n"
    "    pv = prev_prices_test[i]\n"
    "    lr = xgb_log_pred[i]\n"
    "    pp = xgb_price_pred[i]\n"
    "    at = actual_test_prices[i]\n"
    "    print(f'  Baris {i}: prev_price={pv:.4f}, log_ret_pred={lr:.8f}')\n"
    "    print(f'           price_pred = {pv:.4f} x exp({lr:.8f})')\n"
    "    print(f'                      = {pv:.4f} x {np.exp(lr):.8f} = {pp:.4f}')\n"
    "    print(f'           actual     = {at:.4f}')\n"
    "    print(f'           error      = {at - pp:+.4f}')\n"
    "    print()"
))

# Section 14: LightGBM 
cells.append(mid(
    "## 14. Training & Prediksi LightGBM\n\n"
    "LightGBM menggunakan histogram-based learning, lebih cepat dari XGBoost pada dataset besar.\n\n"
    "**Konfigurasi (dari `forecaster.py`):**\n"
    "```python\n"
    "LGBMRegressor(\n"
    "    n_estimators=2000, learning_rate=0.005, max_depth=6, num_leaves=63,\n"
    "    subsample=0.8, subsample_freq=5, colsample_bytree=0.7,\n"
    "    reg_alpha=0.1, reg_lambda=2.0, min_child_samples=15\n"
    ")\n"
    "```"
))

cells.append(code(
    "lgbm_model = LGBMRegressor(\n"
    "    n_estimators=2000, learning_rate=0.005, max_depth=6, num_leaves=63,\n"
    "    subsample=0.8, subsample_freq=5, colsample_bytree=0.7,\n"
    "    reg_alpha=0.1, reg_lambda=2.0, min_child_samples=15,\n"
    "    random_state=42, verbose=-1,\n"
    ")\n"
    "print('Training LightGBM...')\n"
    "lgbm_model.fit(X_train, y_train)\n"
    "print('Selesai.')\n"
    "print()\n\n"
    "lgbm_log_pred   = lgbm_model.predict(X_test)\n"
    "lgbm_price_pred = prev_prices_test * np.exp(lgbm_log_pred)\n\n"
    "print('Prediksi LightGBM untuk 2 baris test:')\n"
    "for i in range(N_TEST):\n"
    "    pv = prev_prices_test[i]\n"
    "    lr = lgbm_log_pred[i]\n"
    "    pp = lgbm_price_pred[i]\n"
    "    at = actual_test_prices[i]\n"
    "    print(f'  Baris {i}: prev_price={pv:.4f}, log_ret_pred={lr:.8f}')\n"
    "    print(f'           price_pred = {pv:.4f} x exp({lr:.8f})')\n"
    "    print(f'                      = {pv:.4f} x {np.exp(lr):.8f} = {pp:.4f}')\n"
    "    print(f'           actual     = {at:.4f}')\n"
    "    print(f'           error      = {at - pp:+.4f}')\n"
    "    print()"
))

# Section 15: Metrics 
cells.append(mid(
    "## 15. Evaluasi Metrik\n\n"
    "| Metrik | Formula | Keterangan |\n"
    "|--------|---------|------------|\n"
    "| **RMSE** | √(Σ(actual−pred)² / n) | Root Mean Square Error (USD) |\n"
    "| **MAE** | Σ|actual−pred| / n | Mean Absolute Error (USD) |\n"
    "| **MAPE** | Σ(|actual−pred|/actual) × 100 / n | Error dalam persen (%) |\n"
    "| **R²** | 1 − SS_res/SS_tot | Koefisien determinasi (1.0 = sempurna) |\n\n"
    "Evaluasi dilakukan pada **2 baris test set**."
))

cells.append(code(
    "actual   = actual_test_prices\n"
    "n        = len(actual)\n\n"
    "print('=' * 65)\n"
    "print('PERBANDINGAN PREDIKSI VS AKTUAL')\n"
    "print('=' * 65)\n"
    "comp = pd.DataFrame({\n"
    "    'Tanggal':    [str(d.date()) for d in df_test['ds']],\n"
    "    'Aktual':     actual,\n"
    "    'XGBoost':    xgb_price_pred,\n"
    "    'LightGBM':   lgbm_price_pred,\n"
    "    'Err_XGB':    actual - xgb_price_pred,\n"
    "    'Err_LGBM':   actual - lgbm_price_pred,\n"
    "})\n"
    "print(comp.to_string(index=False))\n\n"
    "# XGBoost metrics step-by-step\n"
    "print()\n"
    "print('=' * 65)\n"
    "print('METRIK XGBOOST — LANGKAH DEMI LANGKAH')\n"
    "print('=' * 65)\n"
    "xgb_sq   = (actual - xgb_price_pred) ** 2\n"
    "xgb_abs  = np.abs(actual - xgb_price_pred)\n"
    "xgb_pct  = xgb_abs / actual * 100\n\n"
    "print(f'n = {n}')\n"
    "print()\n"
    "print('Squared Errors:')\n"
    "for i in range(n):\n"
    "    print(f'  ({actual[i]:.4f} - {xgb_price_pred[i]:.4f})^2 = {actual[i]-xgb_price_pred[i]:+.6f}^2 = {xgb_sq[i]:.8f}')\n"
    "mse_xgb  = np.mean(xgb_sq)\n"
    "rmse_xgb = np.sqrt(mse_xgb)\n"
    "print(f'  MSE  = ({\" + \".join([f\"{x:.8f}\" for x in xgb_sq])}) / {n} = {mse_xgb:.8f}')\n"
    "print(f'  RMSE = sqrt({mse_xgb:.8f}) = {rmse_xgb:.8f}')\n"
    "print()\n"
    "print('Absolute Errors:')\n"
    "for i in range(n):\n"
    "    print(f'  |{actual[i]:.4f} - {xgb_price_pred[i]:.4f}| = {xgb_abs[i]:.8f}')\n"
    "mae_xgb = np.mean(xgb_abs)\n"
    "print(f'  MAE = ({\" + \".join([f\"{x:.8f}\" for x in xgb_abs])}) / {n} = {mae_xgb:.8f}')\n"
    "print()\n"
    "print('Percentage Errors:')\n"
    "for i in range(n):\n"
    "    print(f'  |{actual[i]:.4f} - {xgb_price_pred[i]:.4f}| / {actual[i]:.4f} x100 = {xgb_pct[i]:.6f}%')\n"
    "mape_xgb = np.mean(xgb_pct)\n"
    "print(f'  MAPE = {mape_xgb:.6f}%')\n"
    "print()\n"
    "mean_actual = np.mean(actual)\n"
    "ss_res_xgb = np.sum((actual - xgb_price_pred)**2)\n"
    "ss_tot     = np.sum((actual - mean_actual)**2)\n"
    "r2_xgb = (1 - ss_res_xgb / ss_tot) if ss_tot > 0 else float('nan')\n"
    "print(f'R2 = 1 - SS_res / SS_tot')\n"
    "print(f'   SS_res = {ss_res_xgb:.8f}')\n"
    "print(f'   SS_tot = sum((actual - mean_actual)^2), mean_actual = {mean_actual:.6f}')\n"
    "for i in range(n):\n"
    "    print(f'     ({actual[i]:.4f} - {mean_actual:.4f})^2 = {(actual[i]-mean_actual)**2:.8f}')\n"
    "print(f'   SS_tot = {ss_tot:.8f}')\n"
    "print(f'   R2  = 1 - {ss_res_xgb:.8f} / {ss_tot:.8f} = {r2_xgb:.8f}')\n\n"
    "# LightGBM metrics\n"
    "print()\n"
    "print('=' * 65)\n"
    "print('METRIK LIGHTGBM — LANGKAH DEMI LANGKAH')\n"
    "print('=' * 65)\n"
    "lgbm_sq  = (actual - lgbm_price_pred) ** 2\n"
    "lgbm_abs = np.abs(actual - lgbm_price_pred)\n"
    "lgbm_pct = lgbm_abs / actual * 100\n"
    "mse_lgbm  = np.mean(lgbm_sq)\n"
    "rmse_lgbm = np.sqrt(mse_lgbm)\n"
    "mae_lgbm  = np.mean(lgbm_abs)\n"
    "mape_lgbm = np.mean(lgbm_pct)\n"
    "ss_res_lgbm = np.sum((actual - lgbm_price_pred)**2)\n"
    "r2_lgbm = (1 - ss_res_lgbm / ss_tot) if ss_tot > 0 else float('nan')\n\n"
    "print(f'n = {n}')\n"
    "print('Squared Errors:')\n"
    "for i in range(n):\n"
    "    print(f'  ({actual[i]:.4f} - {lgbm_price_pred[i]:.4f})^2 = {actual[i]-lgbm_price_pred[i]:+.6f}^2 = {lgbm_sq[i]:.8f}')\n"
    "print(f'  RMSE = sqrt({mse_lgbm:.8f}) = {rmse_lgbm:.8f}')\n"
    "print(f'  MAE  = {mae_lgbm:.8f}')\n"
    "print(f'  MAPE = {mape_lgbm:.6f}%')\n"
    "print(f'  R2   = 1 - {ss_res_lgbm:.8f} / {ss_tot:.8f} = {r2_lgbm:.8f}')"
))

# Section 16: Summary 
cells.append(mid(
    "## 16. Ringkasan Akhir\n\n"
    "Perbandingan lengkap hasil prediksi dan metrik evaluasi.\n\n"
    "> **Catatan penting:** Metrik ini berdasarkan **2 data test saja**.\n"
    "> Dalam aplikasi produksi (`forecaster.py`), model dilatih dengan ~2500 baris (10 tahun)\n"
    "> dan dievaluasi pada 30+ baris test — hasil metrik jauh lebih representatif."
))

cells.append(code(
    "print('=' * 65)\n"
    "print('RINGKASAN AKHIR')\n"
    "print('=' * 65)\n"
    "print()\n"
    "print('Harga Prediksi vs Aktual (USD/troy oz):')\n"
    "summary = pd.DataFrame({\n"
    "    'Tanggal':  [str(d.date()) for d in df_test['ds']],\n"
    "    'Aktual':   [f'${x:.4f}' for x in actual],\n"
    "    'XGBoost':  [f'${x:.4f}' for x in xgb_price_pred],\n"
    "    'LightGBM': [f'${x:.4f}' for x in lgbm_price_pred],\n"
    "    'Err_XGB%': [f'{abs(actual[i]-xgb_price_pred[i])/actual[i]*100:.4f}%' for i in range(n)],\n"
    "    'Err_LGBM%':[f'{abs(actual[i]-lgbm_price_pred[i])/actual[i]*100:.4f}%' for i in range(n)],\n"
    "})\n"
    "print(summary.to_string(index=False))\n"
    "print()\n\n"
    "print('Metrik Evaluasi:')\n"
    "metrics = pd.DataFrame({\n"
    "    'Metrik':   ['RMSE (USD)', 'MAE (USD)', 'MAPE (%)', 'R2'],\n"
    "    'XGBoost':  [f'{rmse_xgb:.6f}',  f'{mae_xgb:.6f}',  f'{mape_xgb:.4f}',  f'{r2_xgb:.6f}'],\n"
    "    'LightGBM': [f'{rmse_lgbm:.6f}', f'{mae_lgbm:.6f}', f'{mape_lgbm:.4f}', f'{r2_lgbm:.6f}'],\n"
    "})\n"
    "print(metrics.to_string(index=False))\n"
    "print()\n"
    "print('Pipeline selesai. Semua angka telah ditampilkan di atas.')"
))

# Assemble notebook 
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells
}

out_path = r"D:\Skripsi 2026\prediksi_silver\kalkulasi_manual.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Notebook ditulis ke: {out_path}")
print(f"Total sel: {len(cells)}")
